config/routes.rb
Rails.application.routes.draw do
  get 'cards/index'
  get 'cards/show'
  get 'genre/index'
  get 'genre/show'
  root to: 'home#index'
  resources :genre, only: :show
  resources :cards, only: [:new, :create, :show]
  namespace :api do
    namespace :v1 do
      resources :words, only: :index
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :genre
end

app/models/card_collection.rb
class CardCollection
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  extend ActiveModel::Translation
  include ActiveModel::AttributeMethods
  include ActiveModel::Validations
  CARD_NUM = 10  # 同時にユーザーを作成する数
  attr_accessor :collection  # ここに作成したルームモデルが格納される

  # 初期化メソッド
  def initialize(attributes = [])
    if attributes.present?
      self.collection = attributes.map do |value|
        Card.new(
          word: value['word'],
          explanation: value['explanation'],
          genre_id: value['genre_id']
        )
      end
    else
      self.collection = CARD_NUM.times.map{ Card.new }
    end
  end

  # レコードが存在するか確認するメソッド
  def persisted?
    false
  end

  def save
    ActiveRecord::Base.transaction do
      collection.each do |result|
        result.save
      end
    end
    rescue
      p 'エラー'
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :cards
end

app/controllers/api/v1/words_controller.rb
class Api::V1::WordsController < ApplicationController
  protect_from_forgery

  rescue_from Exception, with: :render_status_500

  rescue_from ActiveRecord::RecordNotFound, with: :render_status_404

  def index
    cards = Card.all
    render json: cards
  end

  private

  def render_status_404(exception)
    render json: { errors: [exception] }, status: 404
  end

  def render_status_500(exception)
    render json: { errors: [exception] }, status: 500
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
    @genres = Genre.all
    @cards = CardCollection.new
  end

  def create
    @cards = CardCollection.new(cards_params)
    if @cards.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @card = Card.find(params[:id])
  end

  private
  def cards_params
    params.require(:card)
  end

  def room_params
    params.require(:card).permit(:name, :explanation).merge(genre_id: 1)
  end

end

app/controllers/genre_controller.rb
class GenreController < ApplicationController
  def show
    @genre = Genre.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @genres = Genre.all
  end
end

app/helpers/api/v1/words_helper.rb
module Api::V1::WordsHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cards/new.html.erb
<div class="container">
  <div class="Genre">
    <br><br>
    <h4>単語登録</h4>
    <br>
    <%= link_to 'back', root_path %>
    <br><br>
    <br>
    <div class="wrap">
      <%= form_for @cards, url: cards_path do |form| %>
        <% @cards.collection.each do |card| %>
          <%= fields_for 'card[]', card do |f| %>
            <div class="fields">
              <div class="field">
                <%= f.label :ジャンル, class:"label" %>
                <%= f.collection_select :genre_id, Genre.all, :id, :name, { include_blank: true}, class: "input" %>
              </div>
              <div class="field">
                <%= f.label :単語, class:"label" %>
                <%= f.text_field :word, class: "input" %>
              </div>
              <div class="field">
                <%= f.label :解説, class:"label" %>
                <%= f.text_area :explanation, class: "input" %>
              </div>
            </div>
          <% end %>
        <% end %>
        <div class="action">
          <%= form.submit '登録',class:"btn-secondary" %>
        </div>
      <% end %>
    </div>

    <br><br>
  </div>
  <%= link_to 'back', root_path %>
  <br><br>
</div>

app/views/cards/show.html.erb
<div class="container">
  <div class="Genre">
    <br><br>
    <h4>詳細</h4>
    <br>
    <div class="card">
      <div class="card-header">
        単語：
        <%= @card.word %>
      </div>
      <br>
      <div class="card-body">
        解説：
        <%= @card.explanation %>
      </div>
    </div>
    <br>
    <%= link_to 'back', genre_path(@card.genre_id) %>
  </div>
</div>

app/views/genre/show.html.erb
<div class="container">
  <div class="Genre">
    <br><br>
    <h4>詳細</h4>
    <br>
    <%= link_to 'back', root_path %>
    <br><br>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>No</th>
          <th>単語</th>
          <th>Good</th>
          <th>Bad</th>
        </tr>
      </thead>
      <tbody>
        <% @genre.cards.each_with_index do |g, index| %>
          <tr>
            <th scope="row">
              <%= index + 1 %>
            </th>
            <td>
              <%= link_to card_path(g) do %>
                <%= g.word %>
              <% end %>
            </td>
            <td>
              <input type="checkbox">
            </td>
            <td>
              <input type="checkbox">
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>
  <%= link_to 'back', root_path %>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="Genre">
    <br><br>
    <h3>sss-FlashCards</h3>
    <hr>
    <br><br>
    <h4>単語登録</h4>
    <br>
    <%= link_to 'コチラ', new_card_path, class: 'card-link' %>
    <br><br><br>
    <h4>ジャンル　一覧</h4>
    <ul class="Genre-lists">
      <% @genres.each do |g| %>
        <li class="list">
          <%= link_to genre_path(g), class: "badge badge-warning" do %>
            <%= g.name %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SssFlashcards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>